plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
baseurl: /meta

title: Reasoning Machine
description: https://github.com/reasoning-machine/fireworks.git
